version: '3.2'

services:
  jenkins:
    container_name: ${JENKINS_CONTAINER_NAME}
    image: samuelba/blueocean:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ${LOCAL_JENKINS_DIR}:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
      VIRTUAL_PORT: 8080
    user: root

networks:
  default:
    external:
      name: ${NETWORK}
